// Default content for all site sections — used as fallback when DB has no override.
// Content editors in the dashboard can override any of these values.

import { moduleSynopsis } from "@/components/landing/moduleSynopsis";

export type SectionContent = Record<string, string>;
export type AllContent = Record<string, SectionContent>;

const defaults: AllContent = {
  hero: {
    caption: "Treinamento Online",
    headline: "Dentista, construa a reputação que",
    headline_highlight: "faz lotar sua agenda e a clínica crescer.",
    subheadline: "Reputação gera indicação e lota a agenda.\nAgenda cheia constrói clínica e ergue instituto. Tudo nasce no método.",
    author_name: "Dr. Breno Mont'Alverne",
    author_role: "Fundador do Instituto Mont'Alverne",
    author_avatar: "/images/foto-breno.png",
    cta_primary: "Falar com a Equipe",
    cta_secondary: "Ver a trilha completa",
    video_url: "https://player-vz-8aa69477-53f.tv.pandavideo.com.br/embed/?v=d49c541c-010d-4a28-bdf6-80a535639867",
    video_duration: "12:34",
    video_cta: "Assistir apresentação",
    toggles: JSON.stringify([
      { label: "Comunidade", icon: "Users" },
      { label: "Cursos", icon: "BookOpen" },
      { label: "Mentoria ao Vivo", icon: "Radio" },
    ]),
    reassurance: JSON.stringify([
      "+1.500 dentistas formados",
      "Garantia de 15 dias",
    ]),
  },
  problem: {
    caption: "O vale da estagnação",
    title: "Antes de subir,",
    title_faded: "reconheça onde você está",
    description: "Resina, restauração e gestão exigem consciência, método e visão treinada. A maioria dos dentistas está preso no vale — sem o método certo para construir reputação, lotar a agenda e fazer a clínica crescer.",
    obstacles: JSON.stringify([
      { num: "01", title: "A névoa da insegurança", desc: "Você restaura e torce para dar certo. Sem método, cada caso é uma aposta — e a confiança se perde no meio da névoa." },
      { num: "02", title: "Tropeçando na morfologia", desc: "Sem domínio de largura ótica, terços e texturas, seus dentes ficam artificiais. O paciente percebe." },
      { num: "03", title: "No escuro com a cor", desc: "Matiz, croma, valor, opacidade — sem lógica óptica treinada, a escolha da resina vira tentativa e erro." },
    ]),
    quote: "A maior causa da insegurança não é falta de talento — é não ter um guia experiente e uma trilha clara.",
    quote_author: "— Prof. Breno Mont'Alverne",
    cta_url: "https://pay.hotmart.com/F97566234Y?off=68pkkb40&bid=1759193560368",
    cta_text: "Falar com a Equipe",
  },
  modules: {
    caption: "A trilha completa",
    title_line1: "13 acampamentos",
    title_line2: "até o topo",
    subtitle: "Cada módulo é uma etapa da escalada. Cada Hands-On, um treino no terreno real.",
    camps: JSON.stringify([
      { num: "01", altitude: "1.200m", title: "Início da Expedição", desc: "Boas-vindas e mapeamento da jornada. Entenda cada etapa que vai te levar do chão ao cume da odontologia restauradora.", phase: "Base", img: "/images/thumbs/freepik_1-thumb.webp", cover: "/images/capa1.webp" },
      { num: "02", altitude: "1.800m", title: "Princípios do Método Mont'", desc: "20+ anos de experiência clínica condensados em um método progressivo e estratégico.", phase: "Base", img: "/images/thumbs/freepik_2-thumb.webp", cover: "/images/capa2.webp" },
      { num: "03", altitude: "2.400m", title: "Morfologia — Dentes Anteriores", desc: "A fundação do Método. Textura, sulcos, transições, largura ótica. Aprenda a enxergar como um clínico de excelência.", phase: "Ascensão", img: "/images/thumbs/freepik_3-thumb.webp", cover: "/images/capa3.webp" },
      { num: "04", altitude: "3.000m", title: "Morfologia — Dentes Posteriores", desc: "Os 5 pilares da morfologia oclusal: fossas, sulcos, lóbulos, vertentes e arestas.", phase: "Ascensão", img: "/images/thumbs/freepik_4-thumb.webp", cover: "/images/capa4.webp" },
      { num: "05", altitude: "3.600m", title: "Propriedades Ópticas", desc: "Matiz, croma, valor, opacidade, translucidez — a lógica óptica que transforma restaurações em dentes vivos.", phase: "Ascensão", img: "/images/thumbs/freepik_5-thumb.webp", cover: "/images/capa5.webp" },
      { num: "06", altitude: "4.200m", title: "Restauração Classe I e II", desc: "Diagnóstico, matrizes, técnica restauradora e casos clínicos reais.", phase: "Altitude", img: "/images/thumbs/freepik_6-thumb.webp", cover: "/images/capa6.webp" },
      { num: "07", altitude: "4.800m", title: "Restauração Classe III, IV e V", desc: "Domine cor, bisel, estratificação e naturalidade nas restaurações 'simples' que mais derrubam dentistas.", phase: "Altitude", img: "/images/thumbs/freepik_7-thumb.webp", cover: "/images/capa7.webp" },
      { num: "08", altitude: "5.400m", title: "Dentes Extensamente Destruídos", desc: "Procedimentos rotineiros transformados em resultados impecáveis e previsíveis.", phase: "Altitude", img: "/images/thumbs/freepik_8-thumb.webp", cover: "/images/capa8.webp" },
      { num: "09", altitude: "6.000m", title: "Adesão e Fotoativação", desc: "A base da longevidade. Substratos, adesivos e a ciência real por trás da fotoativação.", phase: "Crista", img: "/images/thumbs/freepik_9-thumb.webp", cover: "/images/capa9.webp" },
      { num: "10", altitude: "6.600m", title: "Facetas — Conóides e Diastemas", desc: "Facetas em resina com naturalidade e previsibilidade. Do planejamento ao polimento.", phase: "Crista", img: "/images/thumbs/freepik_10-thumb.webp", cover: "/images/capa10.webp" },
      { num: "11", altitude: "7.200m", title: "Facetas — Casos Complexos", desc: "O trecho mais desafiador da escalada. Resolva qualquer caso anterior com segurança total.", phase: "Crista", img: "/images/thumbs/freepik_11-thumb.webp", cover: "/images/capa11.webp" },
      { num: "12", altitude: "7.800m", title: "Finalização e Polimento", desc: "Acabamento, texturização e polimento — o que separa clínicos comuns de clínicos de excelência.", phase: "Cume", img: "/images/thumbs/freepik_11-thumb.webp", cover: "/images/capa12.webp" },
      { num: "13", altitude: "8.848m", title: "Reabilitação Oral — O CUME", desc: "O topo da montanha. Reabilite sorrisos completos com resina composta.", phase: "Cume", img: "/images/thumbs/freepik_12-thumb.webp", cover: "/images/capa13.webp" },
    ]),
    hands_on: JSON.stringify([
      { num: "H1", title: "Dente Extensamente Destruído Anterior", desc: "Reconstrução coronária com técnica direta — do pino à estratificação final.", img: "/images/handson-cover-1.webp" },
      { num: "H2", title: "Facetas Clareadas", desc: "Estratificação completa de facetas em resina sobre dentes clareados.", img: "/images/handson-cover-2.webp" },
      { num: "H3", title: "Restaurações de Dentes Anteriores", desc: "Técnica restauradora para dentes anteriores com naturalidade e previsibilidade.", img: "/images/handson-cover-3.webp" },
      { num: "H4", title: "Caso Clínico: De Canino a Canino", desc: "Reabilitação anterior completa — planejamento, enceramento e execução.", img: "/images/handson-cover-4.webp" },
      { num: "H5", title: "Clareamento Dental — Curso Extra", desc: "Módulo bônus com Dra. Rayssa Cavaleiro sobre clareamento dental.", img: "/images/handson-cover-5.webp" },
    ]),
  },
  method: {
    caption: "Teoria + Prática",
    title: "Não é só teoria.",
    title_highlight: "É mão na massa.",
    description: "Cada módulo combina embasamento científico com treino prático real.\nVocê aprende o porquê e pratica o como — até dominar.",
    theory_title: "Fundamento Teórico",
    theory_desc: "Aulas gravadas com Prof. Breno explicando cada conceito — morfologia, óptica, adesão, estratificação. Ciência aplicada à clínica real.",
    theory_tags: JSON.stringify(["Morfologia", "Óptica", "Adesão", "Estratificação"]),
    practice_title: "Hands-On Prático",
    practice_desc: "5 imersões práticas com casos reais do Instituto Mont'Alverne. Você opera, esculpe e restaura como se estivesse na bancada.",
    practice_tags: JSON.stringify(["Classe IV", "Facetas", "Polimento", "Enceramento", "Pinos"]),
  },
  instructor: {
    caption: "O guia da expedição",
    title_first: "Prof. Breno",
    title_last: "Mont'Alverne",
    image: "/images/thumbs/breno-thumb.webp",
    bio: JSON.stringify([
      "Dentista há mais de 20 anos, vivi intensamente a odontologia em todas as suas fases. Cada curso é fruto de milhares de horas no consultório, na pesquisa e na sala de aula.",
      "Doutor em Ciências Odontológicas pela FOB-USP. Mestre em Dentística pela FOB-USP. Professor da UFMA e fundador do Instituto Mont'Alverne.",
      "Já guiei mais de 1.500 dentistas nesta escalada. Agora é a sua vez.",
    ]),
    stats: JSON.stringify([
      { value: "20+", label: "anos de clínica", icon: "Mountain" },
      { value: "1.500+", label: "dentistas formados", icon: "Users" },
      { value: "FOB-USP", label: "Doutor e Mestre", icon: "GraduationCap" },
      { value: "UFMA", label: "Professor universitário", icon: "BookOpen" },
    ]),
  },
  benefits: {
    caption: "O que você leva",
    title: "Tudo na sua mochila",
    items: JSON.stringify([
      { title: "Consciência Clínica", desc: "O raciocínio que transforma decisões inseguras em condutas precisas.", num: "01" },
      { title: "Técnica Refinada", desc: "Técnicas modernas que fazem a diferença entre uma restauração mediana e uma obra de naturalidade.", num: "02" },
      { title: "Diferencial Competitivo", desc: "Quando você domina o método, os pacientes percebem. A qualidade se transforma em retorno financeiro.", num: "03" },
      { title: "Imersões Online", desc: "O conteúdo dos cobiçados cursos presenciais do Instituto, acessível de qualquer lugar.", num: "04" },
      { title: "Comunidade de Expedição", desc: "Um grupo exclusivo de dentistas na mesma trilha — troca de experiências e evolução conjunta.", num: "05" },
      { title: "Atualizações Contínuas", desc: "O método evolui com a odontologia. Novos conteúdos são adicionados sem custo extra.", num: "06" },
    ]),
  },
  testimonials: {
    caption: "Depoimentos",
    title: "Quem já fez a escalada",
    subtitle: "Centenas de dentistas já transformaram suas carreiras com o Método Mont'.",
    items: JSON.stringify([
      { name: "Dra. Carolina Mendes", text: "O Método Mont' mudou completamente a forma como eu enxergo a odontologia restauradora. Hoje consigo resultados que antes eu achava impossíveis com resina composta. O Breno é um professor generoso e absurdamente didático.", role: "Dentista Clínica — São Luís, MA", avatar: "/images/testimonials/avatar-1.jpg" },
      { name: "Dr. Rafael Oliveira", text: "Eu já tinha feito outros cursos de resina, mas nenhum me deu a segurança que o Método Mont' me deu. A lógica da morfologia anterior e posterior finalmente fez sentido. Meus pacientes perceberam a diferença.", role: "Especialista em Dentística — Teresina, PI", avatar: "/images/testimonials/avatar-2.jpg" },
      { name: "Dra. Fernanda Rocha", text: "O módulo de propriedades ópticas foi um divisor de águas na minha carreira. Parei de 'decorar cores' e comecei a entender a lógica. Meus casos de faceta em resina hoje são incomparáveis com o que eu fazia antes.", role: "Clínica Geral — Fortaleza, CE", avatar: "/images/testimonials/avatar-3.jpg" },
      { name: "Dr. Lucas Barros", text: "Recém-formado, eu tinha medo de pegar qualquer caso anterior. Depois do Método Mont', fiz minha primeira faceta em resina com confiança total. O passo a passo do Breno elimina completamente a insegurança.", role: "Recém-formado — São Luís, MA", avatar: "/images/testimonials/avatar-4.jpg" },
      { name: "Dra. Isabela Santos", text: "A comunidade do curso é um diferencial absurdo. O nível das discussões, os feedbacks do Breno nos encontros ao vivo, a troca com outros dentistas… tudo isso acelera a evolução de um jeito que nenhum curso gravado faz sozinho.", role: "Dentista Clínica — Belém, PA", avatar: "/images/testimonials/avatar-5.jpg" },
      { name: "Dr. Marcos Almeida", text: "Tenho 18 anos de clínica e achava que sabia restaurar. O Breno me mostrou que eu estava cometendo erros que eu nem percebia — sobrecontorno, bisel errado, fotoativação mal feita. Hoje meus resultados duram muito mais.", role: "Dentista Clínico — Imperatriz, MA", avatar: "/images/testimonials/avatar-6.jpg" },
      { name: "Dra. Amanda Costa", text: "Os Hands-On são incríveis. Ver o Breno executando casos reais do Instituto, com todas as dificuldades e decisões do consultório, é muito mais valioso do que qualquer aula teórica. Isso é ensino de verdade.", role: "Especialista em Prótese — Recife, PE", avatar: "/images/testimonials/avatar-7.jpg" },
      { name: "Dr. Thiago Nascimento", text: "O módulo de Classe I e II transformou meu consultório. Minha taxa de refação caiu drasticamente e meus posteriores hoje duram anos. O conceito de análise estrutural antes de restaurar é genial e simples ao mesmo tempo.", role: "Clínico Geral — Salvador, BA", avatar: "/images/testimonials/avatar-8.jpg" },
      { name: "Dra. Juliana Farias", text: "Eu já indicava o Breno antes mesmo de ele lançar o curso online. Ele é, sem exagero, o melhor professor de dentística que eu já tive. A clareza com que ele explica coisas complexas é um talento raro.", role: "Mestre em Dentística — São Paulo, SP", avatar: "/images/testimonials/avatar-9.jpg" },
      { name: "Dr. André Souza", text: "Depois do curso, abri minha clínica focada em estética com resina. O Método Mont' me deu a base técnica e a confiança para dar esse passo. Melhor investimento que fiz na minha carreira até hoje.", role: "Proprietário de Clínica — São Luís, MA", avatar: "/images/testimonials/avatar-10.jpg" },
      { name: "Dra. Patrícia Lima", text: "O módulo de facetas em casos complexos é de outro nível. Diastemas, conoides, dentes escurecidos — tudo com protocolo claro. Saí do curso sabendo resolver qualquer caso anterior que aparecesse.", role: "Dentista Clínica — Manaus, AM", avatar: "/images/testimonials/avatar-11.jpg" },
      { name: "Dr. Gabriel Moreira", text: "A mentoria ao vivo com o Breno vale o investimento inteiro. Poder mostrar meus casos e receber feedback direto do professor, com toda a turma aprendendo junto, é uma experiência transformadora.", role: "Recém-formado — Brasília, DF", avatar: "/images/testimonials/avatar-12.jpg" },
    ]),
  },
  pricing: {
    caption: "Investimento",
    title: "Sua expedição começa aqui",
    subtitle_label: "Treinamento Online",
    subtitle_desc: "Comunidade + Cursos + Mentorias ao Vivo",
    price_original: "De R$ 3.500,00",
    price_prefix: "12x de",
    price_value: "R$ 165",
    price_cents: ",00",
    price_note: "sem juros · ou R$ 1.980,00 à vista",
    includes: JSON.stringify([
      "13 módulos — do vale ao topo",
      "5 Hands-On com casos reais do Instituto",
      "Aulas objetivas e materiais exclusivos",
      "Suporte próximo da equipe",
      "12 encontros ao vivo com Breno Mont'Alverne (1 por mês)",
      "Atualização permanente de conteúdos",
      "Acesso disponível por 12 meses",
    ]),
    bonus_label: "Bônus da expedição",
    bonus_main_title: "Seja membro fundador da comunidade:",
    bonus_main_name: "Mont'Alverne Experience",
    bonus_main_desc: "Grupo exclusivo no WhatsApp com acesso direto à equipe e outros alunos.",
    bonuses: JSON.stringify([
      "Curso de Clareamento: Dra. Rayssa Cavaleiro",
      "Curso de Fotografia: Dr. Caio Calixto",
      "Curso de I.A. para Dentistas",
    ]),
    cta_text: "Falar com a Equipe",
    guarantee: "Compra segura · Garantia de 15 dias",
  },
  faq: {
    caption: "Perguntas Frequentes",
    title: "Tire suas dúvidas",
    subtitle: "As perguntas mais comuns sobre o treinamento respondidas de forma direta.",
    items: JSON.stringify([
      { q: "Para quem é o Treinamento Mont'Alverne?", a: "Para dentistas que querem dominar restaurações em resina composta com previsibilidade, estética e segurança — independentemente do nível de experiência. Do recém-formado ao profissional experiente que quer refinar a técnica." },
      { q: "Preciso ter experiência prévia com resina?", a: "Não. O método foi desenhado para ser progressivo: começa na base (morfologia e princípios ópticos) e avança até casos complexos como reabilitações completas. Cada etapa prepara para a próxima." },
      { q: "Por quanto tempo terei acesso ao conteúdo?", a: "O acesso é disponível por 12 meses a partir da data da compra. Durante esse período, você também recebe todas as atualizações de conteúdo sem custo adicional." },
      { q: "As aulas são gravadas ou ao vivo?", a: "O treinamento conta com aulas gravadas que você assiste no seu ritmo, além de 12 encontros ao vivo por ano com o Prof. Breno Mont'Alverne para tirar dúvidas e discutir casos clínicos." },
      { q: "Qual a garantia de satisfação?", a: "Você tem 15 dias de garantia incondicional. Se por qualquer motivo sentir que o treinamento não é para você, basta solicitar o reembolso integral — sem burocracia." },
      { q: "Como funciona o suporte?", a: "Você terá suporte próximo da equipe do Instituto para dúvidas sobre o conteúdo, técnicas e casos clínicos. O objetivo é que você nunca se sinta sozinho na jornada." },
      { q: "Posso parcelar o pagamento?", a: "Sim! Oferecemos parcelamento em até 12x no cartão de crédito, além de opções com desconto para pagamento à vista via Pix ou boleto." },
      { q: "Os Hands-On são presenciais?", a: "Os Hands-On incluídos no treinamento online são módulos em vídeo com casos reais do Instituto, onde você acompanha cada etapa do procedimento em detalhes. São projetados para simular a experiência prática o máximo possível." },
    ]),
  },
  footer: {
    tagline: "A expedição até o topo da odontologia restauradora.",
    instagram_links: JSON.stringify([
      { label: "Instituto", url: "https://www.instagram.com/instituto.montalverne/" },
      { label: "Dr. Breno", url: "https://www.instagram.com/bremontalverne/" },
    ]),
  },
  onboarding: {
    hero_eyebrow: "Bem-vindo à expedição",
    hero_title: "Tudo começa",
    hero_title_line2: "aqui,",
    hero_highlight: "agora.",
    hero_description: "Você garantiu acesso completo ao Método Mont. Abaixo estão seus primeiros passos, todos os acessos e o que está na sua mochila.",
    mochila_label: "Na sua mochila",
    mochila_items: JSON.stringify([
      { bold: "13 módulos", text: "— do vale ao topo" },
      { bold: "5 Hands-On", text: "com casos reais do Instituto" },
      { bold: "Suporte próximo", text: "da equipe" },
      { bold: "12 encontros ao vivo", text: "com Breno Mont'Alverne" },
      { bold: "Atualização permanente", text: "de conteúdos" },
      { bold: "12 meses", text: "de acesso disponível" },
    ]),
    access_label: "Seus acessos",
    main_access_url: "https://hotmart.com/pt-br/club/metodo-mont/products/4965259",
    main_access_title: "Acessar o Método Mont — Hotmart",
    main_access_sub: "13 módulos · 5 Hands-On · materiais · encontros ao vivo",
    wa_group_label: "Grupo no WhatsApp",
    wa_group_sub: "Equipe + alunos · acesso direto",
    wa_group_url: "https://chat.whatsapp.com/FC5v8TyMjWvI3XcY0Yy8FZ",
    experience_label: "Mont'Alverne Experience",
    experience_sub: "Comunidade · membro fundador",
    experience_url: "https://chat.whatsapp.com/FC5v8TyMjWvI3XcY0Yy8FZ",
    steps_label: "Como acessar na Hotmart",
    steps_title: "Acesso em 3 passos",
    steps_sub: "Você já tem conta — é só entrar",
    hotmart_steps: JSON.stringify([
      { title: "Acesse o link do curso", desc: "Clique no botão acima e você será redirecionado para a Hotmart." },
      { title: "Faça login com o e-mail da compra", desc: "Sua conta já está ativa e o produto vinculado.", pill: "Use o e-mail da compra" },
      { title: 'Clique em "Assistir agora" e comece', desc: "O Método Mont aparece em Meus produtos." },
    ]),
    bonus_label: "Bônus da expedição",
    bonuses: JSON.stringify([
      { name: "Curso de Clareamento", author: "Dra. Rayssa Cavaleiro", url: "https://hotmart.com/pt-br/club/metodo-mont/products/4965259" },
      { name: "Curso de Fotografia", author: "Dr. Caio Calixto", url: "https://hotmart.com/pt-br/club/metodo-mont/products/4965259" },
      { name: "I.A. para Dentistas", author: "Incluso na trilha", url: "https://hotmart.com/pt-br/club/metodo-mont/products/4965259" },
    ]),
    tip_bold: "Bônus:",
    tip_text: "disponíveis dentro da trilha na Hotmart, em Meus produtos. Esqueceu a senha? Clique em \"Esqueci minha senha\" na tela de login.",
    announcements_label: "Quadro de avisos",
    announcements_sub: "Próximas aulas ao vivo com Breno Mont'Alverne",
    no_announcements_title: "Nenhum aviso no momento",
    no_announcements_desc: "Quando uma aula ao vivo for agendada, a data e o horário aparecerão aqui. O link de acesso será enviado por e-mail.",
    support_label: "Suporte",
    support_links: JSON.stringify([
      { type: "whatsapp", label: "WhatsApp", contact: "(98) 9143-6777", url: "https://wa.me/5598991436777" },
      { type: "email", label: "E-mail", contact: "contato@metodomont.com.br", url: "mailto:contato@metodomont.com.br" },
    ]),
    cta_primary_text: "Começar agora",
    cta_primary_url: "https://hotmart.com/pt-br/club/metodo-mont/products/4965259",
    cta_secondary_text: "Entrar no grupo",
    cta_secondary_url: "https://chat.whatsapp.com/FC5v8TyMjWvI3XcY0Yy8FZ",
  },
  synopses: Object.fromEntries(
    Object.entries(moduleSynopsis).flatMap(([num, data]) => [
      [`synopsis_${num}_title`, data.title],
      [`synopsis_${num}_tagline`, data.tagline],
      [`synopsis_${num}_content`, data.content.join("\n\n")],
    ])
  ),
};

export default defaults;

// Helper to get section labels for the dashboard
export const sectionLabels: Record<string, string> = {
  hero: "Hero (Topo)",
  problem: "Problema (Vale)",
  modules: "Módulos e Sinopses",
  method: "Método (Teoria + Prática)",
  instructor: "Instrutor (O Guia)",
  benefits: "Benefícios (Mochila)",
  testimonials: "Depoimentos",
  pricing: "Investimento (Preço)",
  faq: "Perguntas Frequentes",
  footer: "Rodapé",
  onboarding: "Onboarding",
};

// Helper: labels for each key within a section
export const fieldLabels: Record<string, Record<string, string>> = {
  hero: {
    caption: "Etiqueta superior",
    headline: "Título principal",
    headline_highlight: "Título (destaque dourado)",
    subheadline: "Subtítulo",
    author_name: "Nome do autor",
    author_role: "Cargo do autor",
    author_avatar: "Avatar do autor",
    cta_primary: "Botão principal",
    cta_secondary: "Botão secundário",
    video_url: "URL do vídeo",
    video_duration: "Duração do vídeo",
    video_cta: "Texto do botão de vídeo",
    toggles: "Pílulas de info (JSON)",
    reassurance: "Itens de reassurance (JSON)",
  },
  problem: {
    caption: "Etiqueta superior",
    title: "Título",
    title_faded: "Título (parte desbotada)",
    description: "Descrição",
    obstacles: "Obstáculos (JSON)",
    quote: "Citação",
    quote_author: "Autor da citação",
    cta_url: "URL do botão CTA",
    cta_text: "Texto do botão CTA",
  },
  modules: {
    caption: "Etiqueta superior",
    title_line1: "Título linha 1",
    title_line2: "Título linha 2",
    subtitle: "Subtítulo",
    camps: "Acampamentos / Módulos (JSON)",
    hands_on: "Hands-On (JSON)",
  },
  method: {
    caption: "Etiqueta superior",
    title: "Título",
    title_highlight: "Título (destaque)",
    description: "Descrição",
    theory_title: "Título — Teoria",
    theory_desc: "Descrição — Teoria",
    theory_tags: "Tags de teoria (JSON)",
    practice_title: "Título — Prática",
    practice_desc: "Descrição — Prática",
    practice_tags: "Tags de prática (JSON)",
  },
  instructor: {
    caption: "Etiqueta superior",
    title_first: "Nome (primeira parte)",
    title_last: "Sobrenome (destaque)",
    image: "Foto do instrutor",
    bio: "Parágrafos da bio (JSON)",
    stats: "Estatísticas (JSON)",
  },
  benefits: {
    caption: "Etiqueta superior",
    title: "Título",
    items: "Benefícios (JSON)",
  },
  testimonials: {
    caption: "Etiqueta superior",
    title: "Título",
    subtitle: "Subtítulo",
    items: "Depoimentos (JSON)",
  },
  pricing: {
    caption: "Etiqueta superior",
    title: "Título",
    subtitle_label: "Subtítulo — Label",
    subtitle_desc: "Subtítulo — Descrição",
    price_original: "Preço original (riscado)",
    price_prefix: "Prefixo do preço",
    price_value: "Valor do preço",
    price_cents: "Centavos",
    price_note: "Nota sob o preço",
    includes: "Itens inclusos (JSON)",
    bonus_label: "Label de bônus",
    bonus_main_title: "Título do bônus principal",
    bonus_main_name: "Nome do bônus principal",
    bonus_main_desc: "Descrição do bônus principal",
    bonuses: "Bônus extras (JSON)",
    cta_text: "Texto do botão CTA",
    guarantee: "Texto de garantia",
  },
  faq: {
    caption: "Etiqueta superior",
    title: "Título",
    subtitle: "Subtítulo",
    items: "Perguntas e respostas (JSON)",
  },
  footer: {
    tagline: "Tagline",
    instagram_links: "Links do Instagram (JSON)",
  },
  onboarding: {
    hero_eyebrow: "Etiqueta do hero",
    hero_title: "Título (linha 1)",
    hero_title_line2: "Título (linha 2)",
    hero_highlight: "Destaque dourado",
    hero_description: "Descrição do hero",
    mochila_label: "Label da mochila",
    mochila_items: "Itens da mochila (JSON)",
    access_label: "Label de acessos",
    main_access_url: "URL acesso principal (Hotmart)",
    main_access_title: "Título acesso principal",
    main_access_sub: "Subtítulo acesso principal",
    wa_group_label: "Label grupo WhatsApp",
    wa_group_sub: "Subtítulo grupo WhatsApp",
    wa_group_url: "URL grupo WhatsApp",
    experience_label: "Label Experience",
    experience_sub: "Subtítulo Experience",
    experience_url: "URL Experience",
    steps_label: "Label dos passos",
    steps_title: "Título dos passos",
    steps_sub: "Subtítulo dos passos",
    hotmart_steps: "Passos Hotmart (JSON)",
    bonus_label: "Label dos bônus",
    bonuses: "Bônus (JSON)",
    tip_bold: "Dica (negrito)",
    tip_text: "Dica (texto)",
    announcements_label: "Label do quadro de avisos",
    announcements_sub: "Subtítulo dos avisos",
    no_announcements_title: "Título quando sem avisos",
    no_announcements_desc: "Descrição quando sem avisos",
    support_label: "Label de suporte",
    support_links: "Links de suporte (JSON)",
    cta_primary_text: "Texto botão principal",
    cta_primary_url: "URL botão principal",
    cta_secondary_text: "Texto botão secundário",
    cta_secondary_url: "URL botão secundário",
  },
  synopses: Object.fromEntries(
    Object.entries(moduleSynopsis).flatMap(([num]) => [
      [`synopsis_${num}_title`, `Título do Módulo ${num}`],
      [`synopsis_${num}_tagline`, `Tagline do Módulo ${num}`],
      [`synopsis_${num}_content`, `Conteúdo do Módulo ${num}`],
    ])
  ),
};
