// Synopsis content for each of the 13 modules — cinematic style
export const moduleSynopsis: Record<number, { title: string; tagline: string; content: string[] }> = {
  1: {
    title: "Início da Expedição",
    tagline: "Boas-vindas à jornada do chão ao topo da odontologia.",
    content: [
      "Seja muito bem-vindo(a). É um prazer enorme ter você aqui iniciando essa jornada do chão ao topo da odontologia.",
      "Quem é o Prof. Breno Montalverne?",
      "Meu nome é Breno Montalverne. Sou fundador do Instituto Montalverne, mestre em Dentística e doutor em Materiais Dentários pela USP.",
      "Atuo como coordenador dos cursos de especialização do Instituto Montalverne e professor do curso de Odontologia da Universidade Federal do Maranhão. E, no dia a dia, assim como você, eu também sou dentista clínico.",
      "Ao longo de mais de 20 anos de odontologia, formei mais de 1.500 alunos na graduação e pós.",
    ],
  },
  2: {
    title: "Princípios do Método Mont'",
    tagline: "20+ anos de experiência condensados em um método progressivo e estratégico.",
    content: [
      "O Método Mont é um caminho seguro, construído a partir de mais de 20 anos de experiência clínica, pesquisa, ensino e observação real dos erros e acertos que formam um dentista de excelência.",
      "O curso é estruturado como uma expedição rumo ao topo — uma escalada planejada, progressiva e estratégica. Cada módulo representa uma etapa essencial da subida, conduzindo você do chão ao topo da odontologia restauradora com clareza e segurança.",
      "Nos 13 módulos principais, você aprende desde os fundamentos de morfologia anterior e posterior, passando pelos princípios ópticos da cor, até chegar aos casos clínicos reais mostrados do início ao fim, com raciocínio, execução e naturalidade aplicada.",
      "Aqui você vê a verdade do consultório — não só o \"antes e depois\", mas a realidade da clínica: dificuldades, refações, detalhes, decisões e raciocínio crítico.",
      "Ao longo do curso, você vai perceber que:\n• Sua dificuldade é a mesma de muitos dentistas experientes.\n• Refazer é mais difícil do que fazer — e você aprenderá a evitar essas armadilhas.\n• A prática guiada e consciente é o que constrói a excelência.\n• A participação ativa no grupo e nos exercícios acelera sua evolução.",
      "O Método Mont não espera que você seja perfeito — espera que você se dedique, pratique, pergunte e evolua.",
      "Este é o início da sua escalada. Parabéns pelo primeiro passo.",
    ],
  },
  3: {
    title: "Morfologia — Dentes Anteriores",
    tagline: "A fundação do Método. Aprenda a enxergar como um clínico de excelência.",
    content: [
      "Antes de qualquer restauração anterior se tornar natural, estética e estável, você precisa dominar uma coisa: a lógica anatômica que a natureza criou. Este módulo é a fundação do Método Mont' — o ponto onde você aprende a enxergar como um clínico de excelência.",
      "Aqui você descobre, com clareza inédita, como cérebro, olhos e mãos trabalham juntos para construir naturalidade verdadeira, e não dentes artificiais.",
      "Você vai aprender:\n• Por que o maior desafio não é executar — é enxergar corretamente o que é natural.\n• Como treinar seu olhar: fotografar dentes naturais, preencher a tela e identificar textura, sulcos e transições.\n• A diferença entre morfologia natural e morfologia \"inventada\".\n• Como analisar um sorriso jovem vs. idoso e entender o que muda de idade para idade.",
      "• O papel das estruturas anatômicas: papila, zênite gengival, améias incisais.\n• O conceito crítico de espaço biológico — e como evitar inflamações crônicas por falta de anatomia.\n• A diferença entre largura anatômica e largura ótica — fundamento da estética anterior.\n• Como as cristas marginais definem percepção de forma e tamanho.",
      "• Como definir formato dos dentes (oval, triangular, quadrado, retangular) baseado em: zênite + meia cervical + meia incisal.\n• Textura: como identificar e como não cair no erro de fazer sulcos artificiais e marcados demais.",
      "Você também vai dominar:\n• Por que muitos erros estéticos vêm de sobrecontorno.\n• Como diferenciar estética real de estética artificial.\n• A lógica que conecta função e estética.\n• Como prevenir fraturas repetidas em borda incisal.",
      "Este módulo transforma a forma como você olha para os dentes. Você deixa de restaurar \"como acha bonito\" e passa a construir dentes como a natureza.",
      "Ao final, você será capaz de analisar qualquer sorriso e saber exatamente: o que está errado, por que está errado e como corrigir com precisão. É aqui que nasce a naturalidade verdadeira.",
    ],
  },
  4: {
    title: "Morfologia — Dentes Posteriores",
    tagline: "Domine a função mastigatória, a oclusão e a construção perfeita dos posteriores.",
    content: [
      "Domine a função mastigatória, a oclusão e a construção perfeita dos dentes posteriores.",
      "Depois de aprender a morfologia dos dentes anteriores, chega o momento de dominar a outra metade da naturalidade: a morfologia posterior, onde cada detalhe anatômico define função, conforto e longevidade.",
      "Este módulo revela, de forma clara e didática, os 5 pilares da morfologia oclusal — o mapa completo para você reproduzir dentes posteriores com precisão, estética e função mastigatória perfeita.",
      "Você vai entender:\n• A diferença essencial entre morfologia estética (anteriores) e morfologia funcional (posteriores).\n• Os cinco pilares: arestas, vertentes, fossas, sulcos e lóbulos principais.\n• Como localizar e reproduzir essas estruturas — passo a passo.\n• Como evitar erros clínicos comuns: restauração alta, desconforto, deslize de alimento.",
      "• Por que a ponta da cúspide é a referência principal.\n• A lógica para diferenciar molares superiores e inferiores.\n• Como identificar os pontos de contato funcionais.\n• Como evitar que a anatomia \"bonita\" se perca após o ajuste.",
      "Você também vai descobrir:\n• Por que o pré-molar é considerado difícil — e como torná-lo fácil.\n• Como marcar contatos antes de anestesiar.\n• Como isolar, restaurar e manter a morfologia preservada mesmo após o polimento.",
      "No final deste módulo, você não apenas \"desenha dentinhos\". Você domina a arquitetura funcional dos dentes posteriores. Vai saber exatamente onde colocar cada sulco, cada lóbulo, cada fossa e cada cúspide — não por palpite, mas por método.",
      "É aqui que muitos dentistas desistem… E onde você começa a se diferenciar.",
    ],
  },
  5: {
    title: "Propriedades Ópticas",
    tagline: "A lógica óptica que transforma restaurações em dentes vivos.",
    content: [
      "Depois de dominar a morfologia, você aprende a segunda grande força que define a naturalidade de uma restauração: a cor.",
      "Aqui você entende, de forma clara, objetiva e finalmente aplicável, como funcionam as propriedades ópticas que transformam uma restauração comum em um dente vivo, natural e invisível.",
      "Você vai descobrir:\n• Por que cor não é subjetiva — é falta de treinamento visual.\n• Como construir um olhar treinado para identificar matiz, croma e valor.\n• A importância real da espessura de esmalte e dentina em cada terço do dente.\n• Como escolher a resina ideal para cada situação, evitando erros graves de percepção.",
      "• O impacto da opacidade e translucidez na profundidade do dente restaurado.\n• Como a luz interage com cada camada e por que isso muda totalmente a cor final.\n• Por que a cor verdadeira só aparece após o acabamento e polimento — e como usar isso a seu favor.",
      "Ao final deste módulo, você não \"decora cores\". Você domina a lógica óptica, entende como a luz se comporta, como o dente responde, e como a sua restauração pode finalmente atingir a naturalidade que diferencia iniciantes de clínicos de excelência.",
    ],
  },
  6: {
    title: "Restauração Classe I e II",
    tagline: "A fundação sólida que faz restaurações durarem décadas.",
    content: [
      "Este é o módulo onde você finalmente entende, de forma simples e profundamente clínica, o que faz uma restauração posterior durar 5, 10, 20 e até 30 anos.",
      "Se a morfologia oclusal é o \"cume da montanha\", as restaurações classe 1 e 2 são a fundação sólida — o terreno onde tudo se sustenta.",
      "1. O diagnóstico moderno dos dentes posteriores\nVocê vai entender por que, durante décadas, dentes eram abertos sem critério — e como hoje a decisão é muito mais precisa e conservadora.",
      "2. Longevidade: a verdade que ninguém te contou\nA durabilidade não depende da melhor resina do mundo — mas do operador. O posterior é o melhor dente para treinar e a régua mais clara da sua evolução clínica.",
      "3. Análise estrutural — o coração da decisão clínica\nComo ler a estrutura do dente antes de restaurar: papel da junção amelodentinária, trincas, risco de fratura, tomografia, quando salvar e quando reabilitar.",
      "4. Cúspide fina = fratura certa\nSe a cúspide tem menos de 1,5 mm, ela vai fraturar. Como avaliar, quando rebaixar e como evitar fraturas pós-restauração.",
      "5. O protocolo da BASE\nSelamento dentinário imediato, elevação de margem, como evitar violar o espaço biológico.",
      "6. Matrizes: o segredo da classe 2\nMatrizes seccionais, circunferenciais, pré-formadas, porta-matriz Tofflemire, matrizes de cobre e como eliminar infiltração.",
      "7–10. Cunhas, Resinas, Técnica Restauradora e Casos Clínicos\nEstabilização perfeita, flow/bulk-fill/termoaquecíveis, técnica vertical vs. horizontal, e casos completos de Classe 1 simples até MOD com remoção de amálgama.",
      "No final, você será capaz de diagnosticar, restaurar e finalizar posteriores com longevidade real e função impecável.",
    ],
  },
  7: {
    title: "Restauração Classe III, IV e V",
    tagline: "As restaurações 'simples' que mais derrubam dentistas.",
    content: [
      "Este é o módulo que revela a verdade que quase ninguém comenta: as restaurações consideradas \"simples\" são justamente as que mais fazem dentistas errarem — e serem cobrados pelo paciente.",
      "Classe 3 — A restauração \"simples\" que mais entrega o seu resultado\n• Excesso de dentina → dente branco e opaco\n• Excesso de esmalte → dente acinzentado, com aspecto de cárie\n• Quando usar resina de corpo para equilibrar opacidade e translucidez",
      "Classe 4 — A restauração mais desafiadora dos anteriores\n• Uso estratégico de resina translúcida neutra\n• Equilíbrio preciso entre dentina e esmalte\n• Ajuste funcional: protrusiva e lateralidade\n• Técnica completa: Palatina → Dentina → Esmalte",
      "Classe 5 — Lesões cervicais não cariosas\n• Quando restaurar e quando apenas acompanhar\n• Por que a cor é simples, mas a longevidade é complexa\n• Uso inteligente de resinas monocromáticas",
      "O Bisel — O divisor de águas da naturalidade\nTécnica L.E.I.:\n• L — Longo: 1.5 a 2 mm\n• E — Espesso: profundidade até a junção amelodentinária\n• I — Infinito: transição imperceptível",
      "Ao final, você será capaz de restaurar Classe 3, 4 e 5 com naturalidade, profundidade e previsibilidade — dominando cor, valor, translucidez e opacidade.",
    ],
  },
  8: {
    title: "Dentes Extensamente Destruídos",
    tagline: "Procedimentos rotineiros transformados em resultados impecáveis.",
    content: [
      "As restaurações simples que mais derrubam dentistas — e como dominá-las com precisão de especialista.",
      "Este módulo aprofunda aquilo que todo clínico geral faz todos os dias — mas quase ninguém domina de verdade: as restaurações de Classe 3, Classe 4 e Classe 5.",
      "Você vai aprender:\n• Classificar corretamente classe 3, 4 e 5\n• Como escolher a resina certa para cada classe\n• Erros invisíveis que destroem o resultado: linha branca, linha cinza, excesso de dentina ou esmalte",
      "O bisel perfeito — com a Lei LEI (Longo, Espesso e Infinito):\n• Como medir 1,5 a 2mm de altura\n• Como suavizar a quina do bisel\n• Como mascarar a interface dente–restauração",
      "Classe 4 — O grande desafio:\n• Reconstrução da parede palatina\n• Como criar halo, profundidade e translucidez\n• Ajustes oclusais para longevidade",
      "Classes 5 modernas:\n• Origem ácida e mecânica (bruxismo/apertamento)\n• Como aumentar a longevidade em ambiente úmido\n• Técnicas práticas: mão livre, matriz BRD, moldagem rápida",
      "Casos reais com 4–6 anos de longevidade e o raciocínio de seleção de resina para estabilidade estética ao longo do tempo.",
      "Ao final, você sai do nível \"fazendo o básico\" e entra no nível \"fazendo o básico com excelência\".",
    ],
  },
  9: {
    title: "Adesão e Fotoativação",
    tagline: "A base da longevidade — se errar aqui, toda a escalada vai por água abaixo.",
    content: [
      "O módulo em que você entende, de forma prática, por que não basta escolher uma boa resina: se a adesão e a fotoativação forem mal-feitas, toda a sua escalada vai por água abaixo.",
      "Substratos em detalhes: diferenças entre esmalte, dentina superficial, dentina profunda, dentina esclerosada, hipomineralização, fluorose e dentes com tratamento endodôntico — e como adaptar a técnica em cada caso.",
      "Tipos de adesivos e quando usar cada um: convencional, autocondicionante e universal, com foco nas estratégias mais seguras para dentina profunda e dentes posteriores.",
      "Condicionamento ácido sem medo: tempos ideais em esmalte e dentina, quando NÃO usar ácido, e como evitar sensibilidade pós-operatória.",
      "Aplicação ativa do adesivo: uso correto dos microaplicadores, importância da smear layer, controle de umidade e como evitar \"poças\" de monômero e water trees.",
      "Remoção seletiva de tecido cariado: critérios modernos de preservação, diagnóstico pulpar na prática e como selar cárie remanescente com segurança.",
      "Escolha do fotopolimerizador: LEDs de diferentes gerações, irradiância, colimação, tamanho e angulação da ponta ativa — por que um bom foto vale mais que a resina mais cara.",
      "Ao final, você saberá exatamente como colar a sua resina no dente de forma previsível, evitando sensibilidade, microinfiltração, cárie secundária e falhas precoces.",
    ],
  },
  10: {
    title: "Facetas — Conóides e Diastemas",
    tagline: "O módulo que transforma o sorriso dos seus pacientes e a sua carreira.",
    content: [
      "O módulo mais esperado do curso: onde você aprende, de forma prática e guiada, a criar facetas em resina com naturalidade, estabilidade e previsibilidade — do planejamento ao polimento final.",
      "O que você vai aprender:\n• Indicações reais de faceta com ou sem preparo\n• Facetas sem preparo: como escolher a resina correta e evitar manchamento\n• Atendimento estético de alta demanda\n• Quando o clareamento é obrigatório antes da faceta",
      "Planejamento estético previsível: zênite, papila, arquitetura gengival e análise de sorriso.\n\nEstratificação profissional: incremento translúcido, camada de dentina, sulcos de desenvolvimento, esmalte final e efeitos incisais.",
      "Como evitar dentes \"chapados\" e opacos: por que NUNCA usar apenas dentina em uma faceta.\n\nLongevidade real: a tríade que define durabilidade — técnica + paciente + oclusão.",
      "Dentes escurecidos (o maior desafio clínico):\n• Matiz definido vs. indefinido\n• Como diferenciar o tipo de manchamento\n• Qual resina opacificadora usar\n• Como neutralizar a cor sem acinzentar",
      "Opacificação estratégica, manipulação moderna com guia de silicone, e reparo de facetas fraturadas.",
      "No final, você será capaz de criar facetas em resina previsíveis, naturais e duráveis — sabendo exatamente quando preparar, quando clarear e como conduzir cada caso.",
    ],
  },
  11: {
    title: "Facetas — Casos Complexos",
    tagline: "O módulo mais clínico, profundo e desafiador do Método Mont'.",
    content: [
      "Aqui você aprende a resolver, com precisão e previsibilidade, os casos que realmente colocam a experiência do dentista à prova.",
      "Você vai acompanhar passo a passo situações complexas: diastemas de diferentes tamanhos, dentes conoides, perda de papila, manchamentos, classe IV extensas e combinações de todas essas variáveis em um único caso.",
      "Como avaliar clinicamente um caso complexo: formato, proporção, papila, zênite, manchamento, espaço biológico.\n\nQuando a faceta é apenas a \"última camada\" — e o que precisa ser reconstruído antes.",
      "Diastemas: o protocolo real que funciona\n• Como decidir entre 2 ou 3 etapas\n• Fechamento de diastemas de 0,5 mm a 4+ mm\n• Limites estéticos e quando associar ortodontia",
      "Como prever se a papila vai fechar o black space: regra clínica baseada em radiografia (Tarnow).\n\nEstratégias para dentes conoides: seleção correta de resina, opacificadores, reconstrução de volume.",
      "Dentes escurecidos — o passo a passo completo:\n• Camada opacificadora → Reconstrução → Dentina → Esmalte translúcido\n\nEstratificação avançada em casos mistos: classe IV + faceta + reconstrução interna no mesmo dente.",
      "Os 5 ângulos de visão: método Mont' para acertar forma, proporção e volume.\n\nLongevidade real: casos acompanhados por 9 anos.",
      "Ao finalizar, você será capaz de resolver qualquer caso anterior — simples, médio ou extremamente complexo — com segurança, naturalidade e visão de planejamento. Esse é o módulo que forma restauradores clínicos completos.",
    ],
  },
  12: {
    title: "Finalização e Polimento",
    tagline: "O que separa clínicos comuns de clínicos de excelência.",
    content: [
      "Neste módulo final, você descobre o ponto mais negligenciado — e mais decisivo — para o sucesso de qualquer restauração: o acabamento e o polimento. É aqui que a sua escalada chega ao topo — e onde muitos dentistas caem.",
      "A diferença entre acabamento e polimento — e por que ambos precisam ser executados com precisão cirúrgica.\n\nPor que toda resina, de qualquer marca, nasce porosa e por que essa rugosidade é a principal inimiga da longevidade.",
      "Anatomia primária na prática: forma, tamanho, proporção, arestas proximais, borda incisal.\n\nFerramentas certas para cada fase: broca multilaminada, lâmina 12, discos, borrachas espirais, borrachas tipo chama, lentilha, escovas e pastas.",
      "Região cervical: como remover sobrecontorno sem invadir espaço biológico.\n\nPolimento úmido x polimento seco: evidência científica e microscopia eletrônica.",
      "Texturização superficial: sulcos de desenvolvimento, periquimácias, lóbulos.\n\nComo polir a interproximal sem perder o ponto de contato.\n\nBordas incisais: como preservar a junção palatina/vestibular.",
      "Velocidade correta: 7.000–9.000 rpm para não destruir a resina.\n\nLongevidade real: como dieta, refluxo, hábitos e estilo de vida determinam o prazo de retorno.",
      "Ao finalizar, você entenderá por que acabamento e polimento são o verdadeiro fator de longevidade — e dominará a sequência completa para entregar restaurações lisas, brilhantes e naturais por anos.",
    ],
  },
  13: {
    title: "Reabilitação Oral — O CUME",
    tagline: "A prova definitiva de domínio técnico, visão clínica e planejamento integrado.",
    content: [
      "No módulo final da sua jornada, você chega ao topo da montanha mais alta: a reabilitação oral com resina composta — a prova definitiva de domínio técnico, visão clínica e planejamento integrado.",
      "Aqui você descobre como a resina composta é capaz de reabilitar bocas inteiras com previsibilidade, segurança e longevidade. É o módulo que transforma dentistas habilidosos em clínicos completos.",
      "A Tríade da Longevidade: Técnica correta, Oclusão equilibrada e Comportamento do paciente.\n\nPlanejamento Guiado: como pensar antes de executar, entender riscos e prever resultados.",
      "Ferramentas do Mundo Digital: scanners, centros de planejamento, mockups e integração do articulador analógico ao virtual.\n\nJIG & Intercuspidação: relação cêntrica, interferências e estabilidade.",
      "Mockup com Bisacrílica: como materializar o projeto na boca do paciente.\n\nAnálise Macro → Micro: a reabilitação começa no rosto, passa pelo sorriso e só depois chega ao dente.",
      "Diagnóstico de Desgaste: refluxo, bruxismo, hábitos, postura de sono.\n\nResina como Diagnóstico: quando a resina é melhor que cerâmica para monitorar hábitos.",
      "Casos clínicos completos: do planejamento à execução, incluindo preparo, enceramento, mockup, restaurações diretas e indiretas, ajuste oclusal e finalização.",
      "Ao final, você estará apto a reabilitar sorrisos completos — anteriores e posteriores — com resina composta, unindo ciência, técnica e visão estética. Você dominará o planejamento digital e analógico e saberá executar reabilitações que entregam função, estética e longevidade verdadeira.",
    ],
  },
};
